/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#dee4dd",
        "tertiary-fixed": "#ebddff",
        "inverse-primary": "#006a6a",
        "surface-variant": "#303632",
        error: "#ffb4ab",
        tertiary: "#faf1ff",
        "on-tertiary-fixed-variant": "#5728a5",
        "on-primary-fixed-variant": "#004f4f",
        "surface-container-low": "#171d19",
        "surface-container-lowest": "#0a0f0c",
        "primary-fixed-dim": "#00dddd",
        "on-surface": "#dee4dd",
        "on-secondary-fixed-variant": "#551abb",
        "on-secondary": "#3c0091",
        secondary: "#d0bcff",
        "tertiary-fixed-dim": "#d3bbff",
        "inverse-surface": "#dee4dd",
        "tertiary-container": "#e2d0ff",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#b9cac9",
        "surface-tint": "#00dddd",
        "on-tertiary": "#3f008d",
        "on-error": "#690005",
        "surface-container-high": "#252b27",
        background: "#0f1511",
        "on-primary": "#003737",
        "on-secondary-fixed": "#23005c",
        "on-tertiary-fixed": "#250059",
        "secondary-fixed-dim": "#d0bcff",
        "inverse-on-surface": "#2c322d",
        outline: "#849493",
        primary: "#c7fffe",
        "on-secondary-container": "#c4abff",
        "surface-container-highest": "#303632",
        "primary-fixed": "#2cfbfb",
        "outline-variant": "#3a4a49",
        "on-tertiary-container": "#6e43be",
        "surface-bright": "#343b36",
        "error-container": "#93000a",
        "secondary-container": "#571ebd",
        "surface-container": "#1b211d",
        "on-primary-container": "#006969",
        "primary-container": "#00f0f0",
        "surface-dim": "#0f1511",
        "secondary-fixed": "#e9ddff",
        surface: "#0f1511",
        "on-primary-fixed": "#002020",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};
